export const REGISTER_SUBMIT = 'REGISTER_SUBMIT';
export const REGISTER_SUBMIT_SUCCESS = 'REGISTER_SUBMIT_SUCCESS';

export const SUBMIT_LOGIN_SUCCESS = 'SUBMIT_LOGIN_SUCCESS';

export const SUBMIT_LOG_OUT = 'SUBMIT_LOG_OUT';

export const GET_CURRENT_PROFILE = 'GET_CURRENT_PROFILE';
export const GET_CURRENT_PROFILE_LOADING = 'GET_CURRENT_PROFILE_LOADING';
export const GET_CURRENT_PROFILE_SUCCESS = 'GET_CURRENT_PROFILE_SUCCESS';
export const GET_CURRENT_PROFILE_NOT_FOUND = 'GET_CURRENT_PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';

export const GET_PROFILES_SUCCESS = 'GET_PROFILES_SUCCESS';


export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS'

export const DELETE_PROFILE_SUCCESS = 'DELETE_PROFILE_SUCCESS';

export const ADD_EXPERIENCE_SUCCESS = 'ADD_EXPERIENCE_SUCCESS';
export const ADD_EDUCATION_SUCCESS = 'ADD_EDUCATION_SUCCESS';

export const GET_ERRORS = 'GET_ERRORS';

export const GET_POST_LIST_LOADING = 'GET_POST_LIST_LOADING';
export const GET_POST_LIST_SUCCESS = 'GET_POST_LIST_SUCCESS';

export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';

export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';

export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';

export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';